/* Pas compliqué comme base de données ;) */
CREATE TABLE messages (
    id INT UNSIGNED NOT NUL AUTO_INCREMENT PRIMARY KEY,
    author VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    Date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE=INNODB;